dist: trusty

language: node_js

node_js:
- "8"

if: type = pull_request

env:
  global:
    - BBB_SERVER_URL=http://localhost/bigbluebutton/api

script:
  - travis_wait bash ./build_script.sh

after_script:
  - docker stop $docker
  - docker rm $docker
  - docker rmi b2
