public:
  app:
    mobileFont: 16
    desktopFont: 14
    audioChatNotification: false
    autoJoin: true
    listenOnlyMode: true
    forceListenOnly: false
    skipCheck: false
    clientTitle: BigBlueButton
    appName: BigBlueButton HTML5 Client
    bbbServerVersion: 2.0-rc
    copyright: "Â©2018 BigBlueButton Inc."
    html5ClientBuild: HTML5_CLIENT_VERSION
    lockOnJoin: true
    basename: "/html5client"
    askForFeedbackOnLogout: false
    defaultSettings:
      application:
        chatAudioAlerts: false
        chatPushAlerts: false
        fontSize: 16px
        fallbackLocale: en
      audio:
        inputDeviceId: undefined
        outputDeviceId: undefined
      dataSaving:
        viewParticipantsWebcams: true
        viewScreenshare: true
      cc:
        backgroundColor: "#FFFFFF"
        fontColor: "#000000"
        enabled: false
        fontFamily: Calibri
        fontSize: 16px
        takeOwnership: false
      participants:
        muteAll: false
        lockAll: false
        microphone: false
        publicChat: false
        privateChat: false
        layout: false
    shortcuts:
      openOptions:
        accesskey: O
        descId: openOptions
      toggleUserList:
        accesskey: U
        descId: toggleUserList
      toggleMute:
        accesskey: M
        descId: toggleMute
      joinAudio:
        accesskey: J
        descId: joinAudio
      leaveAudio:
        accesskey: L
        descId: leaveAudio
      togglePublicChat:
        accesskey: P
        descId: togglePublicChat
      hidePrivateChat:
        accesskey: H
        descId: hidePrivateChat
      closePrivateChat:
        accesskey: G
        descId: closePrivateChat
      openActions:
        accesskey: A
        descId: openActions
      openStatus:
        accesskey: S
        descId: openStatus
    branding:
      displayBrandingArea: false
    allowHTML5Moderator: true
    allowModeratorToUnmuteAudio: true
    httpsConnection: false
    connectionTimeout: 60000
    showHelpButton: true
  kurento:
    wsUrl: HOST
    chromeDefaultExtensionKey: akgoaoikmbmhcopjgakkcepdgdgkjfbc
    chromeDefaultExtensionLink: https://chrome.google.com/webstore/detail/bigbluebutton-screenshare/akgoaoikmbmhcopjgakkcepdgdgkjfbc
    chromeExtensionKey: KEY
    chromeExtensionLink: LINK
    chromeScreenshareSources:
    - window
    - screen
    firefoxScreenshareSource: window
    cameraConstraints:
      width:
        max: 640
      height:
        max: 480
    enableScreensharing: false
    enableVideo: false
    enableVideoStats: false
    enableListenOnly: false
    autoShareWebcam: false
  allowOutsideCommands:
    toggleRecording: false
    toggleSelfVoice: false
  poll:
    max_custom: 5
  chat:
    min_message_length: 1
    max_message_length: 5000
    grouping_messages_window: 10000
    type_system: SYSTEM_MESSAGE
    type_public: PUBLIC_ACCESS
    type_private: PRIVATE_ACCESS
    system_userid: SYSTEM_MESSAGE
    system_username: SYSTEM_MESSAGE
    public_id: public
    public_group_id: MAIN-PUBLIC-GROUP-CHAT
    public_userid: public_chat_userid
    public_username: public_chat_username
    storage_key: UNREAD_CHATS
    system_messages_keys:
      chat_clear: PUBLIC_CHAT_CLEAR
  layout:
    autoSwapLayout: false
    hidePresentation: false
  media:
    WebRTCHangupRetryInterval: 2000
    vertoServerAddress: HOST
    freeswitchProfilePassword: '1234'
    vertoPort: '8082'
    useSIPAudio: true
    stunTurnServersFetchAddress: "/bigbluebutton/api/stuns"
    mediaTag: "#remote-media"
    callTransferTimeout: 5000
    callHangupTimeout: 2000
    callHangupMaximumRetries: 10
    echoTestNumber: '9196'
  presentation:
    defaultPresentationFile: default.pdf
    uploadEndpoint: "/bigbluebutton/presentation/upload"
    uploadSizeMin: 0
    uploadSizeMax: 50000000
    uploadValidMimeTypes:
    - application/vnd.ms-excel
    - application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
    - application/msword
    - application/vnd.openxmlformats-officedocument.wordprocessingml.document
    - application/vnd.ms-powerpoint
    - application/vnd.openxmlformats-officedocument.presentationml.presentation
    - application/vnd.oasis.opendocument.text
    - application/rtf
    - text/plain
    - application/vnd.oasis.opendocument.spreadsheet
    - application/vnd.oasis.opendocument.presentation
    - application/vnd.oasis.opendocument.text
    - application/vnd.oasis.opendocument.graphics
    - application/vnd.oasis.opendocument.chart
    - application/vnd.oasis.opendocument.image
    - application/pdf
    - image/jpeg
    - image/png
  user:
    role_moderator: MODERATOR
    role_viewer: VIEWER
    role_presenter: PRESENTER
  whiteboard:
    annotations:
      status:
        start: DRAW_START
        update: DRAW_UPDATE
        end: DRAW_END
    toolbar:
      multiUserPenOnly: false
      colors:
      - label: black
        value: "#000000"
      - label: white
        value: "#ffffff"
      - label: red
        value: "#ff0000"
      - label: orange
        value: "#ff8800"
      - label: eletricLime
        value: "#ccff00"
      - label: Lime
        value: "#00ff00"
      - label: Cyan
        value: "#00ffff"
      - label: dodgerBlue
        value: "#0088ff"
      - label: blue
        value: "#0000ff"
      - label: violet
        value: "#8800ff"
      - label: magenta
        value: "#ff00ff"
      - label: silver
        value: "#c0c0c0"
      thickness:
      - value: 14
      - value: 12
      - value: 10
      - value: 8
      - value: 6
      - value: 4
      - value: 2
      - value: 1
      font_sizes:
      - value: 36
      - value: 32
      - value: 28
      - value: 24
      - value: 20
      - value: 16
      tools:
      - icon: text_tool
        value: text
      - icon: line_tool
        value: line
      - icon: circle_tool
        value: ellipse
      - icon: triangle_tool
        value: triangle
      - icon: rectangle_tool
        value: rectangle
      - icon: pen_tool
        value: pencil
      - icon: hand
        value: hand
      presenterTools:
      - text
      - line
      - ellipse
      - triangle
      - rectangle
      - pencil
      - hand
      multiUserTools:
      - text
      - line
      - ellipse
      - triangle
      - rectangle
      - pencil
      - hand
  clientLog:
    server:
      enabled: true
      level: info
    console:
      enabled: false
      level: debug
    external:
      enabled: false
      level: info
      url: https://LOG_HOST/html5Log
      method: POST
private:
  app:
    captionsChunkLength: 1000
    pencilChunkLength: 100
  redis:
    host: 127.0.0.1
    post: '6379'
    timeout: 5000
    debug: true
    channels:
      toAkkaApps: to-akka-apps-redis-channel
    subscribeTo:
    - to-html5-redis-channel
    - from-akka-apps-*
    async:
    - from-akka-apps-wb-redis-channel
    ignored:
    - CheckAlivePongSysMsg
    - DoLatencyTracerMsg
  serverLog:
    level: info
