# Shared secret of your BigBlueButton server.
bbb:
  serverDomain: myserver.com
  sharedSecret: mysharedsecret
  # Whether to use Auth2.0 or not, Auth2.0 sends the sharedSecret whithin an Authorization header as a bearer
  auth2_0: false
  apiPath: /bigbluebutton/api

# The port in which the API server will run.
server:
  port: 3005

# Web hooks configs
hooks:
  channels:
    - from-akka-apps-redis-channel
    - from-bbb-web-redis-channel
    - from-akka-apps-chat-redis-channel
    - bigbluebutton:from-bbb-apps:meeting
    - bigbluebutton:from-bbb-apps:users
    - bigbluebutton:from-bbb-apps:chat
    - bigbluebutton:from-rap
  # IP where permanent hook will post data (more than 1 URL means more than 1 permanent hook)
  permanentURLs: []
  # How many messages will be enqueued to be processed at the same time
  queueSize: 10000
  # Allow permanent hooks to receive raw message, which is the message straight from BBB
  getRaw: true
  # If set to higher than 1, will send events on the format:
  # "event=[{event1},{event2}],timestamp=000" or "[{event1},{event2}]" (based on using auth2_0 or not)
  # when there are more than 1 event on the queue at the moment of processing the queue.
  multiEvent: 1
  # Retry intervals for failed attempts for perform callback calls.
  # In ms. Totals to around 5min.
  retryIntervals:
    - 100
    - 500
    - 1000
    - 2000
    - 4000
    - 8000
    - 10000
    - 30000
    - 60000
    - 60000
    - 60000
    - 60000
  # Reset permanent interval when exceeding maximum attemps
  permanentIntervalReset: 8
  # Hook's request module timeout for socket conn establishment and/or responses (ms)
  requestTimeout: 5000

# Mappings of internal to external meeting IDs
mappings:
  cleanupInterval: 10000 # 10 secs, in ms
  timeout: 86400000 # 24 hours, in ms

# Redis
redis:
  host: 127.0.0.1
  port: 6379
  keys:
    hookPrefix: bigbluebutton:webhooks:hook
    hooks: bigbluebutton:webhooks:hooks
    mappings: bigbluebutton:webhooks:mappings
    mappingPrefix: bigbluebutton:webhooks:mapping
    eventsPrefix: bigbluebutton:webhooks:events
    userMaps: bigbluebutton:webhooks:userMaps
    userMapPrefix: bigbluebutton:webhooks:userMap
