redis:
  host: '127.0.0.1'
  post: '6379'
  timeout: 5000
  debug: false
  channels:
    toAkkaApps: 'to-akka-apps-redis-channel'
  subscribeTo:
    - 'to-html5-redis-channel'
    - 'from-akka-apps-*'
  async:
    - 'from-akka-apps-wb-redis-channel'
  ignored:
    - 'CheckAlivePongSysMsg'
    - 'DoLatencyTracerMsg'
