kurentoUrl: "ws://HOST/kurento"
kurentoIp: ""
localIpAddress: ""
acceptSelfSignedCertificate: false
redisHost : "127.0.0.1"
redisPort : "6379"
minVideoPort: 30000
maxVideoPort: 33000
from-screenshare: "from-screenshare-redis-channel"
to-screenshare: "to-screenshare-redis-channel"
from-video: "from-video-redis-channel"
to-video: "to-video-redis-channel"
from-audio: "from-audio-redis-channel"
to-audio: "to-audio-redis-channel"
