acl:
  viewer:
    subscriptions:
      - 'users'
      - 'cursor'
      - 'screenshare'
      - 'meetings'
      - 'polls'
      - 'chat'
      - 'presentations'
      - 'annotations'
      - 'slides'
      - 'captions'
      - 'breakouts'
      - 'voiceUsers'
      - 'whiteboard-multi-user'
    methods:
      - 'listenOnlyToggle'
      - 'userLogout'
      - 'setEmojiStatus'
      - 'toggleSelfVoice'
      - 'publishVote'
      - 'sendChat'
  moderator:
    methods:
      - 'assignPresenter'
      - 'kickUser'
      - 'muteUser'
      - 'unmuteUser'
      - 'endMeeting'
      - 'toggleVoice'
      - 'clearPublicChatHistory'
      - 'changeRole'
      - 'ejectUserFromVoice'
  presenter:
    methods:
      - 'assignPresenter'
      - 'switchSlide'
      - 'modifyWhiteboardAccess'
      - 'undoAnnotation'
      - 'clearWhiteboard'
      - 'moveCursor'
      - 'sendAnnotation'
      - 'removePresentation'
      - 'setPresentation'
