acl:
  viewer:
    subscriptions:
      - 'users'
      - 'cursor'
      - 'screenshare'
      - 'meetings'
      - 'polls'
      - 'chat'
      - 'presentations'
      - 'annotations'
      - 'slides'
      - 'captions'
      - 'breakouts'
      - 'voiceUsers'
    methods:
      - 'listenOnlyToggle'
      - 'userLogout'
      - 'setEmojiStatus'
      - 'publishVote'
      - 'sendChat'
  moderator:
    methods:
      - 'assignPresenter'
      - 'kickUser'
      - 'muteUser'
      - 'unmuteUser'
      - 'endMeeting'
      - 'clearPublicChatHistory'
  presenter:
    methods:
      - 'assignPresenter'
      - 'switchSlide'
