#  Application configurations
app:
  # Default font sizes for mobile / desktop
  mobileFont: 16
  desktopFont: 14

  # Audio notification for unread chat message
  audioChatNotification: false

  # Will offer the user to join the audio when entering the meeting
  autoJoinAudio: true
  listenOnly: false
  skipCheck: false

  # Default global variables
  appName: 'BigBlueButton HTML5 Client'
  bbbServerVersion: '2.0-beta'
  copyright: 'Â©2017 BigBlueButton Inc.'
  html5ClientBuild: 'HTML5_CLIENT_VERSION'
  lockOnJoin: true

  # Name displayed in the brower URL
  basename: '/html5client'

  #default settings for session storage
  defaultSettings:
    application:
      chatAudioNotifications: false
      chatPushNotifications: false
      fontSize: '16px'
      locale: 'en'
    audio:
      inputDeviceId: undefined
      outputDeviceId: undefined
    video:
      viewParticipantsWebcams: true
    cc:
      backgroundColor: '#FFFFFF'
      fontColor: '#000000'
      enabled: false
      fontFamily: 'Calibri'
      fontSize: '16px'
      # locale: undefined
      takeOwnership: false
    participants:
      muteAll: false
      lockAll: false
      lockAll: false
      microphone: false
      publicChat: false
      privateChat: false
      layout: false

  # The initial client version has limited moderator capabilities
  # The following flag disables moderator-only features
  allowHTML5Moderator: true
  allowModeratorToUnmuteAudio: true
