# Chat service configurations
chat:
  min_message_length: 1
  max_message_length: 5000
  grouping_messages_window: 60000
  # Chat types
  type_system: 'SYSTEM_MESSAGE'
  type_public: 'PUBLIC_CHAT'
  type_private: 'PRIVATE_CHAT'
  # Chat ids and names
  system_userid: 'SYSTEM_MESSAGE'
  system_username: 'SYSTEM_MESSAGE'
  public_id: 'public'
  public_userid: 'public_chat_userid'
  public_username: 'public_chat_username'
  # Keys
  storage_key: 'UNREAD_CHATS'
  # Chat paths
  path_route: 'users/chat/'
  system_messages_keys:
    chat_clear: 'PUBLIC_CHAT_CLEAR'
