whiteboard:
  #annotation statuses specific to the each type of annotation
  annotations:
    message_frequency: 50
    status:
      start: 'DRAW_START'
      update: 'DRAW_UPDATE'
      end: 'DRAW_END'
  toolbar:
    colors:
      - value: '#000000'
      - value: '#ffffff'
      - value: '#ff0000'
      - value: '#ff8800'
      - value: '#ccff00'
      - value: '#00ff00'
      - value: '#00ffff'
      - value: '#0088ff'
      - value: '#0000ff'
      - value: '#8800ff'
      - value: '#ff00ff'
      - value: '#c0c0c0'
    thickness:
      - value: 14
      - value: 12
      - value: 10
      - value: 8
      - value: 6
      - value: 4
      - value: 2
    font_sizes: 
      - value: 36
      - value: 32
      - value: 28
      - value: 24
      - value: 20
      - value: 16
    tools:
      #text
      - icon: 'text_tool'
        value: 'text'
      #line
      - icon: 'line_tool'
        value: 'line'
      #ellipse
      - icon: 'circle_tool'
        value: 'ellipse'
      #triangle
      - icon: 'triangle_tool'
        value: 'triangle'
      #rectangle
      - icon: 'rectangle_tool'
        value: 'rectangle'
      #pencil
      - icon: 'pen_tool'
        value: 'pencil'
      #pan and zoom hand
      - icon: 'hand'
        value: 'hand'
