name: Merge conflict check
on:
  push:
  pull_request_target:
    types:
      - opened
      - synchronize

permissions:
  contents: read

jobs:
  main:
    permissions:
      pull-requests: write  # for eps1lon/actions-label-merge-conflict to label PRs
    runs-on: ubuntu-latest
    steps:
      - name: Check for dirty pull requests
        uses: eps1lon/actions-label-merge-conflict@v3
        with:
          dirtyLabel: "status: conflict"
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          commentOnDirty: |
              This pull request has conflicts â˜¹
              Please resolve those so we can review the pull request.
              Thanks.
